var podcastsData = [
  {
    id: 1,
    name: "Product Backstage",
    category: "Product",
    description: "Podcast em português com entrevistas de Product Managers de grandes empresas digitais, discutindo atividades e desafios em gestão de produtos (discovery, escalabilidade, liderança, estratégia, etc.).",
    url: "https://productbackstage.com.br",
    spotifyUrl: "https://open.spotify.com/show/3sYHAEEYA9GL6ofW7ZM430",
    imageUrl: "https://cdn-images-3.listennotes.com/podcasts/product-backstage-alexandre-spengler-F8mo30EBRd1-vdkKGMbm_51.1400x1400.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 2,
    name: "Product Guru's",
    category: "Product",
    description: "Podcast brasileiro que conta histórias e experiências do mundo de produtos, com foco em habilidades, metodologias, carreira e tecnologia, reunindo profissionais diversos como designers, desenvolvedores, pesquisadores e agilistas.",
    url: "https://www.productgurus.com.br",
    spotifyUrl: "https://open.spotify.com/show/7uRmxP1l3m9kwrsTYxnIMA",
    imageUrl: "https://cdn-images-3.listennotes.com/podcasts/product-gurus-paulo-chiodi-0tKWhAlp4zD-S_XfDbAzrpw.1400x1400.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 3,
    name: "Mulheres de Produto",
    category: "Product",
    description: "Podcast da comunidade Mulheres de Produto, com conversas e histórias de mulheres que atuam com produtos digitais – desafios de carreira, transições, liderança, diversidade e aprendizado na área de produtos.",
    url: "https://www.mulheresdeproduto.com",
    spotifyUrl: "https://open.spotify.com/show/1rfUWxL2Ia7kA343ClLya1",
    imageUrl: "https://cdn-images-3.listennotes.com/podcasts/mulheres-de-produto-mulheres-de-produto-3wGiUxEm8cY-yufiHj3SERJ.1400x1400.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 4,
    name: "Mesa de Produto",
    category: "Product",
    description: "Podcast da escola PM3 sobre produtos digitais. Apresenta episódios do Mestre de Produto e Mesa de Produto, cobrindo temas de gestão de produtos, inovação, tecnologia e carreira em Produto no Brasil.",
    url: "https://open.spotify.com/show/1g4ZtzpcrfxpYrTMPDzyp9",
    spotifyUrl: "https://open.spotify.com/show/4toanSui1dYx3JWcU36IXl?si=678f5ee901bc4569&nd=1&dlsi=6c515059ba7143b6",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a6c23c22f0c31b17ce8332024",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 5,
    name: "Desenhando Produtos",
    category: "Design de Produto",
    description: "Podcast brasileiro sobre pessoas, produtos e design – discutindo liderança, carreira, diversidade, qualidade de vida e outros temas ligados ao desenvolvimento de produtos e UX.",
    url: "https://desenhandoprodutos.com.br/",
    spotifyUrl: "https://open.spotify.com/show/3yc1MJPrWIOCY3fcrRS2Ke",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1f606ffe0babc7a813b1a7a56d",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 6,
    name: "Papo de Produto",
    category: "Product",
    description: "Podcast brasileiro com conversas aprofundadas sobre o universo de produtos digitais. Traz discussões e entrevistas focadas em práticas de produto, tendências do mercado e experiências reais de profissionais da área.",
    url: "https://papodeproduto.com.br",
    spotifyUrl: "https://open.spotify.com/show/6deUaOxztKmZZFE97FzhFg",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a74e544a4eb881b2a7fedea3d",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 7,
    name: "Produtei",
    category: "Product",
    description: "Podcast brasileiro que traz bate-papos sobre como é a vida de profissionais de produto (“produteiros”). Cada episódio explora vivências, aprendizados de carreira e desafios do dia a dia em gestão de produtos.",
    url: "https://linktr.ee/produtei",
    spotifyUrl: "https://open.spotify.com/show/7GdOeSmAPYaClJ8r4hnT5Y",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a3c9f59bf741e783205116f45",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 8,
    name: "Produto pelo Mundo",
    category: "Product",
    description: "Podcast brasileiro onde Guilherme Seabra entrevista profissionais de produto que atuam fora do Brasil. Cada episódio aprofunda as experiências de carreira internacionais e visões de mercado de product managers brasileiros pelo mundo.",
    url: "https://produtopelomundo.captivate.fm",
    spotifyUrl: "https://open.spotify.com/show/5PD1bRaJz3irxq712zF566",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a9d7e40dd3c4e97f146d77e94",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 9,
    name: "Lança Produto",
    category: "Product Marketing",
    description: "Primeiro podcast brasileiro dedicado a Product Marketing. Discutindo estratégias de lançamento, posicionamento de produto, go-to-market e o papel do marketing de produto no sucesso de produtos digitais.",
    url: "https://open.spotify.com/show/5me9vqby9qz7nRkn9trrkF",
    spotifyUrl: "https://open.spotify.com/show/3xChxQsDToX7gLLHGUo8qk",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a8ed5e9c54596db88cfe604fe",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 10,
    name: "Ladies That UX (PT)",
    category: "UX",
    description: "Podcast em língua portuguesa da comunidade global Ladies That UX. Lançado em 2020, traz convidadas para falar sobre o mundo de UX, desenvolvimento pessoal e temas relevantes às profissionais de UX, conectando comunidades do Brasil e Portugal.",
    url: "https://open.spotify.com/show/4DmywMfuVmXTfIwX9mXocM",
    spotifyUrl: "https://open.spotify.com/show/16VEzBdLGk5vjrONXuTs4j",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a46d918a8638bff22339eb5c0",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 11,
    name: "Movimento UX",
    category: "UX",
    description: "Um dos primeiros podcasts de UX do Brasil, criado em 2016 por Izabela de Fátima. Apresenta entrevistas com profissionais brasileiros de UX compartilhando experiências em agências, startups e grandes empresas, abrangendo UX Research, inovação, empreendedorismo e design de serviços.",
    url: "https://www.movimentoux.com",
    spotifyUrl: "https://open.spotify.com/show/0jpGW9nTFzzzHCjm7Y3d73",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8ad0220850080e4d148078e763",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 12,
    name: "Papo de UX",
    category: "UX",
    description: "Podcast brasileiro lançado em 2020 por Luan Santana (designer). Cada episódio traz convidados da comunidade de UX para discutir habilidades necessárias, desafios do dia a dia e a inserção do design nas organizações.",
    url: "https://open.spotify.com/show/6TFTUN45sn0xuqruzlK2Te",
    spotifyUrl: "https://open.spotify.com/show/32hSv5mp77ocPcd3fPrLjU",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a41e6fdb39dd6cbda1db0f609",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 13,
    name: "Hipsters Ponto Tech",
    category: "Tecnologia",
    description: "Podcast brasileiro produzido pela Caelum/Alura desde 2016. Embora foque em tecnologia e programação, traz episódios sobre design, cultura de produto digital e tendências, sendo uma ponte entre desenvolvimento, design e negócios.",
    url: "https://hipsters.tech",
    spotifyUrl: "https://open.spotify.com/show/2p0Vx75OmfsXktyLBuLuSf",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a3b3d4a3ba041479a6cd35b1c",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 14,
    name: "This is Product Management",
    category: "Product",
    description: "Podcast em inglês que apresenta entrevistas com grandes mentes por trás de produtos e estratégias. Aborda aspectos práticos do cotidiano em gestão de produtos, tendências emergentes e ferramentas modernas para equipes de produto.",
    url: "https://tipm.disqo.com",
    spotifyUrl: "https://open.spotify.com/show/5qoM5evv8FUvaqkSY6OHzn",
    imageUrl: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts125/v4/26/8a/31/268a3162-eca9-269b-6ab6-5b42d1b3ae6b/mza_2146734621143909327.png/1200x1200bf-60.jpg",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 16,
    name: "Lenny's Podcast",
    category: "Product",
    description: "Podcast (em inglês) do Lenny Rachitsky com entrevistas de líderes em produto e experts em growth. Foca em conselhos acionáveis, insights de carreira e estratégias de crescimento de produto, combinando experiências práticas e visão de mercado.",
    url: "https://www.lennysnewsletter.com",
    spotifyUrl: "https://open.spotify.com/show/2dR1MUZEHCOnz1LVfNac0j",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8af45f22d94c8aea326e8bf861",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 18,
    name: "One Knight in Product",
    category: "Product",
    description: "Podcast (em inglês) apresentado por Jason Knight (Reino Unido). Entrevista profissionais de produto, marketing, startups e liderança para explorar a fundo o mundo de gestão de produtos, incluindo diversidade, inclusão e desafios do setor.",
    url: "https://www.oneknightinproduct.com",
    spotifyUrl: "https://open.spotify.com/show/5mt9FHLE7MbsuUjH4YNx7T",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8aa730075cc8ce566ff336f81e",
    language: "Inglês",
    country: "Reino Unido",
    flag: "🇬🇧"
  },
  {
    id: 19,
    name: "Masters of Scale",
    category: "Inovação",
    description: "Podcast (em inglês) apresentado por Reid Hoffman, cofundador do LinkedIn. Aborda histórias de inovação e crescimento exponencial, entrevistando empreendedores e líderes de empresas de sucesso para desvendar estratégias de escala de negócios e produtos.",
    url: "https://mastersofscale.com",
    spotifyUrl: "https://open.spotify.com/show/1bJRgaFZHuzifad4IAApFR",
    imageUrl: "https://yt3.googleusercontent.com/HdjioXDOV4SjrsCwh9z_DAQAt04-Vtls32Zp2GhI2LxX18P6J6h5j4gxWyusCpb458z6AIFP=s900-c-k-c0x00ffffff-no-rj",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 20,
    name: "How I Built This",
    category: "Inovação",
    description: "Podcast de empreendedorismo (em inglês) da NPR apresentado por Guy Raz. Explora as histórias por trás de startups e grandes empresas, com fundadores contando como conceberam, lançaram e escalaram produtos e negócios inovadores, incluindo sucessos e fracassos no caminho.",
    url: "https://www.npr.org/podcasts/510313/how-i-built-this",
    spotifyUrl: "https://open.spotify.com/show/6E709HRH7XaiZrMfgtNCun",
    imageUrl: "https://is1-ssl.mzstatic.com/image/thumb/Podcasts126/v4/64/45/06/644506b5-c44f-f661-f74e-f63a4b2511bc/mza_14892199991035639268.jpeg/1200x1200bf.webp",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 21,
    name: "Rocketship.fm",
    category: "Product",
    description: "Podcast (em inglês) que aborda produtos e startups, com histórias reais de empreendedores e lições práticas de produto. Apresentado por Michael Sacca e Mike Belsito, traz discussões sobre estratégias de produto, inovação, liderança e crescimento de negócios.",
    url: "https://rocketship.fm",
    spotifyUrl: "https://open.spotify.com/show/5kcEHIj6RjVMTNBAx3ONVr",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8abb3dc7c516df97b9e3d1d4d4",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 22,
    name: "Product Love",
    category: "Product",
    description: "Podcast (em inglês) apresentado por Eric Boduch, cofundador da Pendo. Traz entrevistas com gerentes de produto de empresas populares, discutindo como criam produtos amados pelos usuários, tendências da área e dicas para profissionais de produto.",
    url: "https://productcraft.com/podcast/",
    spotifyUrl: "https://open.spotify.com/show/7EEOkGGhmVnqHY4CNNrZDv",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1f434f0bb169a119531411aa8b",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 23,
    name: "Product Thinking",
    category: "Product",
    description: "Podcast (em inglês) apresentado por Melissa Perri, focado em discutir as questões mais comuns na gestão de produtos. Em cada episódio, Melissa e convidados exploram estratégias de produto, liderança, processos e respondem dúvidas frequentes de profissionais da área.",
    url: "https://produxlabs.com",
    spotifyUrl: "https://open.spotify.com/show/3TV1jXZqlSFCzZ3xqvcG96",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a9b5ceea11210bfa64c363fb9",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 24,
    name: "What is Wrong with UX?",
    category: "UX",
    description: "Podcast (em inglês) descontraído sobre UX, apresentado pelas especialistas Laura Klein e Kate Rutter. Com tom bem-humorado, discute desafios do design de experiência, desde motivação e pesquisa de usuários até tendências e más práticas a serem evitadas em UX.",
    url: "https://podcasts.apple.com/us/podcast/what-is-wrong-with-ux/id1047833083",
    spotifyUrl: "https://open.spotify.com/show/4hf2et6iEWhbmlowRKjV7J",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a3bb7492df8dc870127119a5c",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 25,
    name: "Design Better Podcast",
    category: "Design de Produto",
    description: "Podcast (em inglês) focado em design e estratégia de produto, produzido pela InVision. Em cada episódio, líderes de design e produto discutem o papel do design nas empresas, colaboração entre design e desenvolvimento, design inclusivo e como comunicar o valor do design.",
    url: "https://www.designbetter.co/podcast",
    spotifyUrl: "https://open.spotify.com/show/59RliaMdeDAkEgp9nj1Mkj",
    imageUrl: "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F4266a623-293d-4c3f-9c07-01e5df27db39_1280x1280.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 26,
    name: "Metric: The UX Design Podcast",
    category: "UX",
    description: "Podcast (em inglês) apresentado por Michael Schofield, explorando design de experiência do usuário e estratégia de forma objetiva. Episódios curtos cobrem tópicos específicos – de entrevistas com usuários e personas até service design – sempre com dicas práticas para designers.",
    url: "https://soundcloud.com/metricpodcast",
    spotifyUrl: "https://open.spotify.com/show/3dy4Py0mtX1aFfQHDGVgLg",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a4cd0cf22a513f3c5beeb0cb6",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 27,
    name: "Design Life",
    category: "Design de Produto",
    description: "Podcast (em inglês) voltado a designers de produto que buscam equilibrar carreira e projetos pessoais. Apresentado por duas designers, foca em desafios do dia a dia do design, desenvolvimento de carreira e experiências de tocar projetos paralelos (‘side projects’).",
    url: "https://designlife.fm",
    spotifyUrl: "https://open.spotify.com/show/60VdDbOqh5NAqa82JRsZRq",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a65825b30650bc0c44c29b9b2",
    language: "Inglês",
    country: "Nova Zelândia",
    flag: "🇳🇿"
  },
  {
    id: 28,
    name: "Hablemos de Producto",
    category: "Product",
    description: "Podcast em espanhol que explora as histórias, aprendizados e desafios de líderes de produto na América Latina. Cada episódio apresenta conversas autênticas e práticas sobre criação de produtos digitais, estratégias de sucesso e lições de carreira no mundo de produto.",
    url: "https://open.spotify.com/show/5WhLD3xtfQW9bxM7z8H8y2",
    spotifyUrl: "https://open.spotify.com/show/1zgWdozbQM9YkGE5n5YkGg",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1f95143bf676a4a27a3e2b7cb6",
    language: "Espanhol",
    country: "México",
    flag: "🇲🇽"
  },
  {
    id: 29,
    name: "Más Producto",
    category: "Product",
    description: "Podcast de Product Management em espanhol que ajuda a compreender melhor a gestão de produtos, ferramentas, processos e experiências no desenvolvimento de produtos digitais. Apresentado por Melvin Zaldaña, traz entrevistas semanais com profissionais de produto compartilhando práticas e insights.",
    url: "https://masproducto.com",
    spotifyUrl: "https://open.spotify.com/show/1iDYFTDWApquSLNmIAERXM",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1f4cc1e40b22879569cc09dbdd",
    language: "Espanhol",
    country: "Honduras",
    flag: "🇭🇳"
  },
  {
    id: 30,
    name: "Quiero Ser Product Manager",
    category: "Product",
    description: "Podcast em espanhol voltado a aspirantes a gestores de produto e entusiastas de inovação. Aborda desde o processo de transformar uma ideia em um produto real, estratégias como Product-Led Growth, até entrevistas com profissionais para entender as diferentes facetas e tendências em Product Management.",
    url: "https://open.spotify.com/show/0yO5pkb3l4TRE8JwS90rAD",
    spotifyUrl: "https://open.spotify.com/show/0yO5pkb3l4TRE8JwS90rAD",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8ae0db4a1c9b134d54ce1b027c",
    language: "Espanhol",
    country: "Argentina",
    flag: "🇦🇷"
  },
  {
    id: 31,
    name: "Tenemos que hablar de producto",
    category: "Product",
    description: "Podcast em espanhol (Espanha) no qual os hosts Álvaro e Juan entrevistam, a cada mês, um profissional de produto que enfrenta desafios reais na profissão (além dos cenários das big techs). Traz aprendizados práticos e histórias honestas sobre a gestão de produtos em diferentes contextos.",
    url: "https://www.alvaroperezbello.com/podcast",
    spotifyUrl: "https://open.spotify.com/show/4vFFTDBFl9VdFcaaaru6Zq",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSICSFc0AgdpfcMTKxqi4kEcqxGzLhiRC9bmA&s",
    language: "Espanhol",
    country: "Espanha",
    flag: "🇪🇸"
  },
  {
    id: 32,
    name: "Oído Producto",
    category: "Product",
    description: "Podcast em espanhol produzido pela Thiga (consultoria de produto). Apresentado por Blanca Aguirre e Inés Velasco, traz conversas mensais com convidados especiais – profissionais que contam como fazem produto digital em empresas de ponta – abordando reflexões e aprendizados em Product Management e Product Design.",
    url: "https://media.thiga.co/podcast",
    spotifyUrl: "https://open.spotify.com/show/4fKqppGUXozCVYXjhqni5o",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a856f32b4425c0033a780fbca",
    language: "Espanhol",
    country: "Espanha",
    flag: "🇪🇸"
  },
  {
    id: 33,
    name: "Growth (Product Hackers)",
    category: "Growth",
    description: "Podcast em espanhol (anteriormente chamado En.Digital) focado em negócios digitais e Growth. Semanalmente, José Carlos Cortizo (Corti) entrevista os principais nomes de startups e empresas de rápido crescimento, revelando táticas reais de como esses negócios crescem e alcançam sucesso.",
    url: "https://producthackers.com",
    spotifyUrl: "https://open.spotify.com/show/19NNz5WnrGvP7EElm4XsUn",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a18babc1694fcc9a053cfe95c",
    language: "Espanhol",
    country: "Espanha",
    flag: "🇪🇸"
  },
  {
    id: 35,
    name: "The Product-LatAm Podcast",
    category: "Product",
    description: "Podcast (em espanhol) com conversas com líderes que estão transformando negócios na América Latina. Explora temas de produto, tecnologia e growth, trazendo perspectivas regionais sobre gestão de produtos e inovação em startups e empresas latino-americanas.",
    url: "https://open.spotify.com/show/0tLnfs263l9vCUZDYUhM1C",
    spotifyUrl: "https://open.spotify.com/show/0tLnfs263l9vCUZDYUhM1C",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1fdf0125d5d4ab637389bb7525",
    language: "Espanhol",
    country: "Colômbia",
    flag: "🇨🇴"
  },
  {
    id: 37,
    name: "Papo na Arena",
    category: "Product",
    description: "Papo na Arena é o podcast da Product Arena sobre o mundo de produtos digitais, tecnologia e comportamento com comentários dos nossos hosts Arthur Castro (@arthurklose) e Aíquis Rodrigues (@aiquis).",
    url: "https://productarena.io",
    spotifyUrl: "https://open.spotify.com/show/7lcBkPYn5HgEZjTkJhNUFJ",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1fc2a42fc48b0e6edb17c4be99",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 38,
    name: "Deep Growth",
    category: "Growth",
    description: "Podcast brasileiro apresentado por Tahiana D'Egmont e Gabriel Costa (Growth Leaders Academy), com entrevistas aprofundadas sobre estratégias de crescimento e marketing digital, impulsionando carreiras de líderes de growth no Brasil",
    url: "https://growthleaders.academy/podcasts/",
    spotifyUrl: "https://open.spotify.com/show/41HIlBruf8r0kHiAQCyHNp",
    imageUrl: "https://cdn-images.dzcdn.net/images/talk/714e666ff0211244bb6d34269e53fe58/0x1900-000000-80-0-0.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 40,
    name: "Growthaholics",
    category: "Growth",
    description: "Podcast da ACE Startups para os apaixonados por empreendedorismo e inovação corporativa, trazendo conversas provocativas sobre o futuro dos negócios",
    url: "https://aceventures.com.br/conteudos/",
    spotifyUrl: "https://open.spotify.com/show/4373mqNv8l63GDQRdjpaHF",
    imageUrl: "https://ugc.production.linktr.ee/DTZDiaSkQxWYoc0fSsOx_3GC6q572JVscF4VP?io=true&size=avatar-v3_0",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 42,
    name: "In Depth",
    category: "Startup / Negócios",
    description: "Podcast da First Round Review com conselhos práticos de líderes de startups para fazer suas empresas crescerem, em conversas aprofundadas sobre gestão, produto e empreendedorismo",
    url: "https://review.firstround.com/podcast",
    spotifyUrl: "https://i.scdn.co/image/ab67656300005f1f553043939ed32b1c754c86bc",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1f553043939ed32b1c754c86bc",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 43,
    name: "The Ticket",
    category: "Tecnologia",
    description: "Podcast da Intercom em que o time entrevista profissionais do mundo de produto, design, startups e marketing, explorando tendências e histórias do universo tech",
    url: "https://soundcloud.com/intercom",
    spotifyUrl: "https://open.spotify.com/show/6zlcXgcd2kX9E4cbQTCsR9",
    imageUrl: "https://cachedimages.podchaser.com/256x256/aHR0cHM6Ly9jb250ZW50LnByb2R1Y3Rpb24uY2RuLmFydDE5LmNvbS9pbWFnZXMvZjQvOTMvNGMvYmIvZjQ5MzRjYmItOWIzYS00OWVkLWI2ZDktMTAyMmQ1NGU1YTE5L2M4NzZkZThkNzI1MjE1NTc2ZGNiYTcxYTE3ZjMzNzFmZTViMzEyOTg3OTU3YTA5MTI3N2QxZmIyOThlMDkyNTYwMGM3YWE5Mzg5ZDA0MTMwMjU0ZWNjMDI4MzBiOWFjYjk4ZjZlZDkzZTQxNmYwY2FjY2ViOWJjOGM0Mjk3Y2M0LmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 44,
    name: "Intercom on Product",
    category: "Product",
    description: "Podcast da Intercom com insights dos líderes de produto Des Traynor e Paul Adams sobre como construir software em um mundo orientado por IA",
    url: "https://art19.com/shows/intercom-on-product",
    spotifyUrl: "https://open.spotify.com/show/6d9s4PBzvdESARqUadlCpo?si=kPQuIZP0S5WBmzv2WomP-A&nd=1&dlsi=208e1af921684604",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a8cf791f57963bfbff4e52b57",
    language: "Inglês",
    country: "Irlanda / EUA",
    flag: "🇺🇸"
  },
  {
    id: 45,
    name: "Like a Boss",
    category: "Negócios / Startups",
    description: "Podcast brasileiro de empreendedorismo com entrevistas a fundadores e CEOs de startups inovadoras, explorando suas jornadas e decisões de negócio",
    url: "https://www.likeaboss.com.br",
    spotifyUrl: "https://open.spotify.com/show/5qFSRB3x4SP9xZgr4my7fO",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8af993fa824dac4962f4dd61c8",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 47,
    name: "Product Hunt Radio",
    category: "Tecnologia",
    description: "Podcast semanal do Product Hunt com pessoas que estão criando e explorando o futuro da tecnologia. Apresentado por Ryan Hoover e Abadesi Osunsade, traz fundadores, investidores, jornalistas e makers discutindo as últimas novidades em tech",
    url: "https://product-hunt-radio.simplecast.com",
    spotifyUrl: "https://open.spotify.com/show/4Ak6HpbVkLKGacY3E0GHL8",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8aa7c7f529af5755265d21257d",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 49,
    name: "Product Talk",
    category: "Product",
    description: "Podcast da comunidade Products That Count que acompanha a jornada de grandes líderes de produto – conversando sobre o que faz um produto de sucesso e como melhor servir seus usuários",
    url: "https://productsthatcount.com/tag/podcast/",
    spotifyUrl: "https://open.spotify.com/show/3yM6oR3QD2chAFdSXAgzzK",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a95d9b62fe055f10a8f6f3631",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 51,
    name: "The Product Experience",
    category: "Product",
    description: "Podcast semanal do Mind the Product com conversas entre Lily Smith, Randy Silver e grandes profissionais de produto do mundo, focando em insights reais para aprimorar práticas de produto",
    url: "https://www.mindtheproduct.com/the-product-experience/",
    spotifyUrl: "https://open.spotify.com/show/7pv0JHF2YGgXm8OGz1JnL0",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a29284352bd1dbb1c7d0aff9a",
    language: "Inglês",
    country: "Reino Unido",
    flag: "🇬🇧"
  },
  {
    id: 52,
    name: "The Product Podcast (Product School)",
    category: "Product",
    description: "Podcast da Product School com entrevistas sinceras com executivos de produto das maiores empresas de tecnologia do mundo, compartilhando estratégias e práticas de gestão de produtos",
    url: "https://productschool.com/resources/product-podcast",
    spotifyUrl: "https://open.spotify.com/show/1XBrhVLsQOIAv3KFBqnzrX",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1f2bfe2e96b66b0fd2539b7cdb",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 53,
    name: "UI Breakfast: UI/UX Podcast",
    category: "UX",
    description: "Podcast da designer Jane Portman sobre UX/UI e estratégia de produto. Conversas empolgantes com especialistas sobre design de interfaces, SaaS, marketing e muito mais, com dicas acionáveis para aplicar no seu negócio",
    url: "https://uibreakfast.com",
    spotifyUrl: "https://open.spotify.com/show/1mpwVsWRVGB7SfBWqZJbAb",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a84a90b6933512e3efd294da8",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  }
]
