var podcastsData = [
  {
    id: 1,
    name: "Product Backstage",
    category: "Product",
    description: "Podcast em português com entrevistas de Product Managers de grandes empresas digitais, discutindo atividades e desafios em gestão de produtos (discovery, escalabilidade, liderança, estratégia, etc.).",
    url: "https://productbackstage.com.br",
    spotifyUrl: "https://open.spotify.com/show/3sYHAEEYA9GL6ofW7ZM430",
    imageUrl: "https://cdn-images-3.listennotes.com/podcasts/product-backstage-alexandre-spengler-F8mo30EBRd1-vdkKGMbm_51.1400x1400.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 2,
    name: "Product Guru's",
    category: "Product",
    description: "Podcast brasileiro que conta histórias e experiências do mundo de produtos, com foco em habilidades, metodologias, carreira e tecnologia, reunindo profissionais diversos como designers, desenvolvedores, pesquisadores e agilistas.",
    url: "https://www.productgurus.com.br",
    spotifyUrl: "https://open.spotify.com/show/2s0dYJ3GjOaoecImQqEoNi",
    imageUrl: "https://cdn-images-3.listennotes.com/podcasts/product-gurus-paulo-chiodi-0tKWhAlp4zD-S_XfDbAzrpw.1400x1400.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 3,
    name: "Mulheres de Produto",
    category: "Product",
    description: "Podcast da comunidade Mulheres de Produto, com conversas e histórias de mulheres que atuam com produtos digitais – desafios de carreira, transições, liderança, diversidade e aprendizado na área de produtos.",
    url: "https://www.mulheresdeproduto.com",
    spotifyUrl: "https://open.spotify.com/show/6XF1MeoCU5OdZaSUUYOtiL",
    imageUrl: "https://cdn-images-3.listennotes.com/podcasts/mulheres-de-produto-mulheres-de-produto-3wGiUxEm8cY-yufiHj3SERJ.1400x1400.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 4,
    name: "PM3 Talks",
    category: "Product",
    description: "Podcast da escola PM3 sobre produtos digitais. Apresenta episódios do Mestre de Produto e Mesa de Produto, cobrindo temas de gestão de produtos, inovação, tecnologia e carreira em Produto no Brasil.",
    url: "https://open.spotify.com/show/1g4ZtzpcrfxpYrTMPDzyp9",
    spotifyUrl: "https://open.spotify.com/show/1g4ZtzpcrfxpYrTMPDzyp9",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 5,
    name: "Desenhando Produtos",
    category: "Design de Produto",
    description: "Podcast brasileiro sobre pessoas, produtos e design – discutindo liderança, carreira, diversidade, qualidade de vida e outros temas ligados ao desenvolvimento de produtos e UX.",
    url: "https://desenhandoprodutos.com.br/",
    spotifyUrl: "https://open.spotify.com/show/3yc1MJPrWIOCY3fcrRS2Ke",
    imageUrl: "https://i.scdn.co/image/ab67656300005f1f606ffe0babc7a813b1a7a56d",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 6,
    name: "Papo de Produto",
    category: "Product",
    description: "Podcast brasileiro com conversas aprofundadas sobre o universo de produtos digitais. Traz discussões e entrevistas focadas em práticas de produto, tendências do mercado e experiências reais de profissionais da área.",
    url: "https://papodeproduto.com.br",
    spotifyUrl: "https://open.spotify.com/show/0J6IIGOdS7pGTp8T08BJLK",
    imageUrl: "https://cdn-images.dzcdn.net/images/talk/714e666ff0211244bb6d34269e53fe58/0x1900-000000-80-0-0.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 7,
    name: "Produtei",
    category: "Product",
    description: "Podcast brasileiro que traz bate-papos sobre como é a vida de profissionais de produto (“produteiros”). Cada episódio explora vivências, aprendizados de carreira e desafios do dia a dia em gestão de produtos.",
    url: "https://linktr.ee/produtei",
    spotifyUrl: "https://open.spotify.com/show/0A5Ku6NCENkQf4a63eFumU",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 8,
    name: "Produto pelo Mundo",
    category: "Product",
    description: "Podcast brasileiro onde Guilherme Seabra entrevista profissionais de produto que atuam fora do Brasil. Cada episódio aprofunda as experiências de carreira internacionais e visões de mercado de product managers brasileiros pelo mundo.",
    url: "https://produtopelomundo.captivate.fm",
    spotifyUrl: "https://open.spotify.com/show/0lo7vZhaeON3XV0rpaLMdM",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 9,
    name: "Lança Produto",
    category: "Product Marketing",
    description: "Primeiro podcast brasileiro dedicado a Product Marketing. Discutindo estratégias de lançamento, posicionamento de produto, go-to-market e o papel do marketing de produto no sucesso de produtos digitais.",
    url: "https://open.spotify.com/show/5me9vqby9qz7nRkn9trrkF",
    spotifyUrl: "https://open.spotify.com/show/5me9vqby9qz7nRkn9trrkF",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 10,
    name: "Ladies That UX (PT)",
    category: "UX",
    description: "Podcast em língua portuguesa da comunidade global Ladies That UX. Lançado em 2020, traz convidadas para falar sobre o mundo de UX, desenvolvimento pessoal e temas relevantes às profissionais de UX, conectando comunidades do Brasil e Portugal.",
    url: "https://open.spotify.com/show/4DmywMfuVmXTfIwX9mXocM",
    spotifyUrl: "https://open.spotify.com/show/4DmywMfuVmXTfIwX9mXocM",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 11,
    name: "Movimento UX",
    category: "UX",
    description: "Um dos primeiros podcasts de UX do Brasil, criado em 2016 por Izabela de Fátima. Apresenta entrevistas com profissionais brasileiros de UX compartilhando experiências em agências, startups e grandes empresas, abrangendo UX Research, inovação, empreendedorismo e design de serviços.",
    url: "https://www.movimentoux.com",
    spotifyUrl: "https://open.spotify.com/show/0mH7z4ylWyHOYv1gxQM0H1",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 12,
    name: "Papo de UX",
    category: "UX",
    description: "Podcast brasileiro lançado em 2020 por Luan Santana (designer). Cada episódio traz convidados da comunidade de UX para discutir habilidades necessárias, desafios do dia a dia e a inserção do design nas organizações.",
    url: "https://open.spotify.com/show/6TFTUN45sn0xuqruzlK2Te",
    spotifyUrl: "https://open.spotify.com/show/6TFTUN45sn0xuqruzlK2Te",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 13,
    name: "Hipsters Ponto Tech",
    category: "Tecnologia",
    description: "Podcast brasileiro produzido pela Caelum/Alura desde 2016. Embora foque em tecnologia e programação, traz episódios sobre design, cultura de produto digital e tendências, sendo uma ponte entre desenvolvimento, design e negócios.",
    url: "https://hipsters.tech",
    spotifyUrl: "https://open.spotify.com/show/1KXrBdMG5UHdQ3MX0rwRFJ",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 14,
    name: "This is Product Management",
    category: "Product",
    description: "Podcast em inglês que apresenta entrevistas com grandes mentes por trás de produtos e estratégias. Aborda aspectos práticos do cotidiano em gestão de produtos, tendências emergentes e ferramentas modernas para equipes de produto.",
    url: "https://tipm.disqo.com",
    spotifyUrl: "https://open.spotify.com/show/1cZfz4gHgB5iak0YILzpzB",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 15,
    name: "The Product Podcast",
    category: "Product",
    description: "Podcast semanal do Product School com conversas francas com líderes de produto das maiores empresas de tecnologia (Google, Meta, Netflix, etc.). Oferece insights práticos, frameworks e estratégias inovadoras em gestão de produto.",
    url: "https://productschool.com/the-product-podcast",
    spotifyUrl: "https://open.spotify.com/show/4loPdndLrX6g85jEoK0H0C",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 16,
    name: "Lenny's Podcast",
    category: "Product",
    description: "Podcast (em inglês) do Lenny Rachitsky com entrevistas de líderes em produto e experts em growth. Foca em conselhos acionáveis, insights de carreira e estratégias de crescimento de produto, combinando experiências práticas e visão de mercado.",
    url: "https://www.lennysnewsletter.com",
    spotifyUrl: "https://open.spotify.com/show/0CUxMBeQGGD8fw8kGzZxca",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 17,
    name: "The Product Experience",
    category: "Product",
    description: "Podcast semanal (em inglês) da Mind the Product, apresentado por Lily Smith e Randy Silver. Em cada episódio, profissionais de produto do mundo todo compartilham aprendizados reais e dicas práticas para aprimorar as práticas de gestão de produtos.",
    url: "https://www.mindtheproduct.com/the-product-experience/",
    spotifyUrl: "https://open.spotify.com/show/3N9dxTH6Lq2LibpBJgH6kB",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Reino Unido",
    flag: "🇬🇧"
  },
  {
    id: 18,
    name: "One Knight in Product",
    category: "Product",
    description: "Podcast (em inglês) apresentado por Jason Knight (Reino Unido). Entrevista profissionais de produto, marketing, startups e liderança para explorar a fundo o mundo de gestão de produtos, incluindo diversidade, inclusão e desafios do setor.",
    url: "https://www.oneknightinproduct.com",
    spotifyUrl: "https://open.spotify.com/show/4MMhk0cbXC76xgP0xB8BvF",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Reino Unido",
    flag: "🇬🇧"
  },
  {
    id: 19,
    name: "Masters of Scale",
    category: "Inovação",
    description: "Podcast (em inglês) apresentado por Reid Hoffman, cofundador do LinkedIn. Aborda histórias de inovação e crescimento exponencial, entrevistando empreendedores e líderes de empresas de sucesso para desvendar estratégias de escala de negócios e produtos.",
    url: "https://mastersofscale.com",
    spotifyUrl: "https://open.spotify.com/show/0Ky7BKgkI3a5QoZ0v0x8od",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 20,
    name: "How I Built This",
    category: "Inovação",
    description: "Podcast de empreendedorismo (em inglês) da NPR apresentado por Guy Raz. Explora as histórias por trás de startups e grandes empresas, com fundadores contando como conceberam, lançaram e escalaram produtos e negócios inovadores, incluindo sucessos e fracassos no caminho.",
    url: "https://www.npr.org/podcasts/510313/how-i-built-this",
    spotifyUrl: "https://open.spotify.com/show/7jGQXMWuEU7mBot1DfvXFG",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 21,
    name: "Rocketship.fm",
    category: "Product",
    description: "Podcast (em inglês) que aborda produtos e startups, com histórias reais de empreendedores e lições práticas de produto. Apresentado por Michael Sacca e Mike Belsito, traz discussões sobre estratégias de produto, inovação, liderança e crescimento de negócios.",
    url: "https://rocketship.fm",
    spotifyUrl: "https://open.spotify.com/show/4OM3IU7KoLriwzgPJNssBJ",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 22,
    name: "Product Love",
    category: "Product",
    description: "Podcast (em inglês) apresentado por Eric Boduch, cofundador da Pendo. Traz entrevistas com gerentes de produto de empresas populares, discutindo como criam produtos amados pelos usuários, tendências da área e dicas para profissionais de produto.",
    url: "https://productcraft.com/podcast/",
    spotifyUrl: "https://open.spotify.com/show/6vHPrMnkQlYFbWhRuZuuLA",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 23,
    name: "Product Thinking",
    category: "Product",
    description: "Podcast (em inglês) apresentado por Melissa Perri, focado em discutir as questões mais comuns na gestão de produtos. Em cada episódio, Melissa e convidados exploram estratégias de produto, liderança, processos e respondem dúvidas frequentes de profissionais da área.",
    url: "https://produxlabs.com",
    spotifyUrl: "https://open.spotify.com/show/4KpA9UUikZ4xve9Iff3rvs",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 24,
    name: "What is Wrong with UX?",
    category: "UX",
    description: "Podcast (em inglês) descontraído sobre UX, apresentado pelas especialistas Laura Klein e Kate Rutter. Com tom bem-humorado, discute desafios do design de experiência, desde motivação e pesquisa de usuários até tendências e más práticas a serem evitadas em UX.",
    url: "https://podcasts.apple.com/us/podcast/what-is-wrong-with-ux/id1047833083",
    spotifyUrl: "https://open.spotify.com/show/4I8xXVYUzpHHyvylMrOmyh",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 25,
    name: "Design Better Podcast",
    category: "Design de Produto",
    description: "Podcast (em inglês) focado em design e estratégia de produto, produzido pela InVision. Em cada episódio, líderes de design e produto discutem o papel do design nas empresas, colaboração entre design e desenvolvimento, design inclusivo e como comunicar o valor do design.",
    url: "https://www.designbetter.co/podcast",
    spotifyUrl: "https://open.spotify.com/show/59RliaMdeDAkEgp9nj1Mkj",
    imageUrl: "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F4266a623-293d-4c3f-9c07-01e5df27db39_1280x1280.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 26,
    name: "Metric: The UX Design Podcast",
    category: "UX",
    description: "Podcast (em inglês) apresentado por Michael Schofield, explorando design de experiência do usuário e estratégia de forma objetiva. Episódios curtos cobrem tópicos específicos – de entrevistas com usuários e personas até service design – sempre com dicas práticas para designers.",
    url: "https://soundcloud.com/metricpodcast",
    spotifyUrl: "https://open.spotify.com/show/2PaNRFIkZd7xoyVdNGZYNT",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 27,
    name: "Design Life",
    category: "Design de Produto",
    description: "Podcast (em inglês) voltado a designers de produto que buscam equilibrar carreira e projetos pessoais. Apresentado por duas designers, foca em desafios do dia a dia do design, desenvolvimento de carreira e experiências de tocar projetos paralelos (‘side projects’).",
    url: "https://designlife.fm",
    spotifyUrl: "https://open.spotify.com/show/60VdDbOqh5NAqa82JRsZRq",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a65825b30650bc0c44c29b9b2",
    language: "Inglês",
    country: "Nova Zelândia",
    flag: "🇳🇿"
  },
  {
    id: 28,
    name: "Hablemos de Producto",
    category: "Product",
    description: "Podcast em espanhol que explora as histórias, aprendizados e desafios de líderes de produto na América Latina. Cada episódio apresenta conversas autênticas e práticas sobre criação de produtos digitais, estratégias de sucesso e lições de carreira no mundo de produto.",
    url: "https://open.spotify.com/show/5WhLD3xtfQW9bxM7z8H8y2",
    spotifyUrl: "https://open.spotify.com/show/5WhLD3xtfQW9bxM7z8H8y2",
    imageUrl: "podcast.png",
    language: "Espanhol",
    country: "México",
    flag: "🇲🇽"
  },
  {
    id: 29,
    name: "Más Producto",
    category: "Product",
    description: "Podcast de Product Management em espanhol que ajuda a compreender melhor a gestão de produtos, ferramentas, processos e experiências no desenvolvimento de produtos digitais. Apresentado por Melvin Zaldaña, traz entrevistas semanais com profissionais de produto compartilhando práticas e insights.",
    url: "https://masproducto.com",
    spotifyUrl: "https://open.spotify.com/show/1iDYFTDWApquSLNmIAERXM",
    imageUrl: "podcast.png",
    language: "Espanhol",
    country: "Honduras",
    flag: "🇭🇳"
  },
  {
    id: 30,
    name: "Quiero Ser Product Manager",
    category: "Product",
    description: "Podcast em espanhol voltado a aspirantes a gestores de produto e entusiastas de inovação. Aborda desde o processo de transformar uma ideia em um produto real, estratégias como Product-Led Growth, até entrevistas com profissionais para entender as diferentes facetas e tendências em Product Management.",
    url: "https://open.spotify.com/show/0yO5pkb3l4TRE8JwS90rAD",
    spotifyUrl: "https://open.spotify.com/show/0yO5pkb3l4TRE8JwS90rAD",
    imageUrl: "podcast.png",
    language: "Espanhol",
    country: "Argentina",
    flag: "🇦🇷"
  },
  {
    id: 31,
    name: "Tenemos que hablar de producto",
    category: "Product",
    description: "Podcast em espanhol (Espanha) no qual os hosts Álvaro e Juan entrevistam, a cada mês, um profissional de produto que enfrenta desafios reais na profissão (além dos cenários das big techs). Traz aprendizados práticos e histórias honestas sobre a gestão de produtos em diferentes contextos.",
    url: "https://www.alvaroperezbello.com/podcast",
    spotifyUrl: "https://open.spotify.com/show/4vFFTDBFl9VdFcaaaru6Zq",
    imageUrl: "podcast.png",
    language: "Espanhol",
    country: "Espanha",
    flag: "🇪🇸"
  },
  {
    id: 32,
    name: "Oído Producto",
    category: "Product",
    description: "Podcast em espanhol produzido pela Thiga (consultoria de produto). Apresentado por Blanca Aguirre e Inés Velasco, traz conversas mensais com convidados especiais – profissionais que contam como fazem produto digital em empresas de ponta – abordando reflexões e aprendizados em Product Management e Product Design.",
    url: "https://media.thiga.co/podcast",
    spotifyUrl: "https://open.spotify.com/show/3jCWDJzOcmvVLLoRfjap5z",
    imageUrl: "podcast.png",
    language: "Espanhol",
    country: "Espanha",
    flag: "🇪🇸"
  },
  {
    id: 33,
    name: "Growth (Product Hackers)",
    category: "Growth",
    description: "Podcast em espanhol (anteriormente chamado En.Digital) focado em negócios digitais e Growth. Semanalmente, José Carlos Cortizo (Corti) entrevista os principais nomes de startups e empresas de rápido crescimento, revelando táticas reais de como esses negócios crescem e alcançam sucesso.",
    url: "https://producthackers.com",
    spotifyUrl: "https://open.spotify.com/show/19NNz5WnrGvP7EElm4XsUn",
    imageUrl: "https://i.scdn.co/image/ab6765630000ba8a18babc1694fcc9a053cfe95c",
    language: "Espanhol",
    country: "Espanha",
    flag: "🇪🇸"
  },
  {
    id: 34,
    name: "Producto Digital",
    category: "UX",
    description: "Podcast em espanhol apresentado por Jorge Sánchez. Discute produtos digitais e tecnologia sempre do ponto de vista do usuário. Ideal para quem busca entender desenvolvimento de produtos digitais com foco em experiência do usuário.",
    url: "https://jorge.link",
    spotifyUrl: "https://open.spotify.com/show/4kzu3cIxxI7uR9gZ8WiL0P",
    imageUrl: "podcast.png",
    language: "Espanhol",
    country: "Espanha",
    flag: "🇪🇸"
  },
  {
    id: 35,
    name: "The Product-LatAm Podcast",
    category: "Product",
    description: "Podcast (em espanhol) com conversas com líderes que estão transformando negócios na América Latina. Explora temas de produto, tecnologia e growth, trazendo perspectivas regionais sobre gestão de produtos e inovação em startups e empresas latino-americanas.",
    url: "https://open.spotify.com/show/0tLnfs263l9vCUZDYUhM1C",
    spotifyUrl: "https://open.spotify.com/show/0tLnfs263l9vCUZDYUhM1C",
    imageUrl: "podcast.png",
    language: "Espanhol",
    country: "Colômbia",
    flag: "🇨🇴"
  },
  {
    id: 36,
    name: "Lenny's Podcast",
    category: "Product",
    description: "Podcast apresentado por Lenny Rachitsky, com entrevistas aprofundadas sobre gestão de produtos, crescimento (growth), estratégias e insights com líderes e especialistas de empresas renomadas no mercado digital.",
    url: "https://www.lennysnewsletter.com",
    spotifyUrl: "https://open.spotify.com/show/0CUxMBeQGGD8fw8kGzZxca",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 37,
    name: "Papo na Arena",
    category: "Product",
    description: "Papo na Arena é o podcast da Product Arena sobre o mundo de produtos digitais, tecnologia e comportamento com comentários dos nossos hosts Arthur Castro (@arthurklose) e Aíquis Rodrigues (@aiquis).",
    url: "https://productarena.io",
    spotifyUrl: "https://open.spotify.com/show/7lcBkPYn5HgEZjTkJhNUFJ",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 38,
    name: "Deep Growth",
    category: "Growth",
    description: "Podcast brasileiro apresentado por Tahiana D'Egmont e Gabriel Costa (Growth Leaders Academy), com entrevistas aprofundadas sobre estratégias de crescimento e marketing digital, impulsionando carreiras de líderes de growth no Brasil",
    url: "https://growthleaders.academy/podcasts/",
    spotifyUrl: "https://open.spotify.com/show/41HIlBruf8r0kHiAQCyHNp",
    imageUrl: "https://cdn-images.dzcdn.net/images/talk/714e666ff0211244bb6d34269e53fe58/0x1900-000000-80-0-0.jpg",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 40,
    name: "Growthaholics",
    category: "Growth",
    description: "Podcast da ACE Startups para os apaixonados por empreendedorismo e inovação corporativa, trazendo conversas provocativas sobre o futuro dos negócios",
    url: "https://aceventures.com.br/conteudos/",
    spotifyUrl: "https://open.spotify.com/show/4373mqNv8l63GDQRdjpaHF",
    imageUrl: "https://ugc.production.linktr.ee/DTZDiaSkQxWYoc0fSsOx_3GC6q572JVscF4VP?io=true&size=avatar-v3_0",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 41,
    name: "How to Build a Product",
    category: "Product",
    description: "Podcast em inglês que explora a jornada de criar produtos digitais de sucesso, com convidados compartilhando como transformar ideias em produtos reais (práticas de mercado, desafios e aprendizados).",
    url: "",
    spotifyUrl: "",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 42,
    name: "In Depth",
    category: "Startup / Negócios",
    description: "Podcast da First Round Review com conselhos práticos de líderes de startups para fazer suas empresas crescerem, em conversas aprofundadas sobre gestão, produto e empreendedorismo",
    url: "https://review.firstround.com/podcast",
    spotifyUrl: "https://open.spotify.com/show/0zhZc5wSOFzrHCOioWSg0o",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 43,
    name: "Inside Intercom Podcast",
    category: "Tecnologia",
    description: "Podcast da Intercom em que o time entrevista profissionais do mundo de produto, design, startups e marketing, explorando tendências e histórias do universo tech",
    url: "https://soundcloud.com/intercom",
    spotifyUrl: "https://open.spotify.com/show/6zlcXgcd2kX9E4cbQTCsR9",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 44,
    name: "Intercom on Product",
    category: "Product",
    description: "Podcast da Intercom com insights dos líderes de produto Des Traynor e Paul Adams sobre como construir software em um mundo orientado por IA",
    url: "https://art19.com/shows/intercom-on-product",
    spotifyUrl: "https://open.spotify.com/show/6d9s4PBzvdESARqUadlCpo",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Irlanda / EUA",
    flag: "🇺🇸"
  },
  {
    id: 45,
    name: "Like a Boss",
    category: "Negócios / Startups",
    description: "Podcast brasileiro de empreendedorismo com entrevistas a fundadores e CEOs de startups inovadoras, explorando suas jornadas e decisões de negócio",
    url: "https://www.likeaboss.com.br",
    spotifyUrl: "https://open.spotify.com/show/5qFSRB3x4SP9xZgr4my7fO",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 46,
    name: "Prodcast Brasil",
    category: "Tecnologia",
    description: "Podcast brasileiro da Concrete sobre tecnologia e produtos digitais",
    url: "https://concrete.com.br",
    spotifyUrl: "https://open.spotify.com/show/3NkxAeUgBiYvmWTCpB7ocj",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 47,
    name: "Product Hunt Radio",
    category: "Tecnologia",
    description: "Podcast semanal do Product Hunt com pessoas que estão criando e explorando o futuro da tecnologia. Apresentado por Ryan Hoover e Abadesi Osunsade, traz fundadores, investidores, jornalistas e makers discutindo as últimas novidades em tech",
    url: "https://product-hunt-radio.simplecast.com",
    spotifyUrl: "https://open.spotify.com/show/0C0QxFb4gQa89UIhuDg7Jr",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 48,
    name: "Product Oversee",
    category: "Product",
    description: "Portal brasileiro de gestão de produtos, com conteúdo colaborativo que estimula o pensamento crítico sobre liderança e inovação em produtos digitais",
    url: "https://productoversee.com",
    spotifyUrl: "",
    imageUrl: "podcast.png",
    language: "Português",
    country: "Brasil",
    flag: "🇧🇷"
  },
  {
    id: 49,
    name: "Product Talk",
    category: "Product",
    description: "Podcast da comunidade Products That Count que acompanha a jornada de grandes líderes de produto – conversando sobre o que faz um produto de sucesso e como melhor servir seus usuários",
    url: "https://productsthatcount.com/tag/podcast/",
    spotifyUrl: "https://open.spotify.com/show/3yM6oR3QD2chAFdSXAgzzK",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 50,
    name: "Product to Product",
    category: "Product",
    description: "Podcast da Roadmunk com conversas francas entre profissionais de produto, trocando experiências práticas sobre gestão de produtos digitais",
    url: "https://roadmunk.com/product-to-product-podcast/",
    spotifyUrl: "https://open.spotify.com/show/4rbibgKTXCW3W1mWaEcuIF",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Canadá",
    flag: "🇨🇦"
  },
  {
    id: 51,
    name: "The Product Experience",
    category: "Product",
    description: "Podcast semanal do Mind the Product com conversas entre Lily Smith, Randy Silver e grandes profissionais de produto do mundo, focando em insights reais para aprimorar práticas de produto",
    url: "https://www.mindtheproduct.com/the-product-experience/",
    spotifyUrl: "https://open.spotify.com/show/7pv0JHF2YGgXm8OGz1JnL0",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Reino Unido",
    flag: "🇬🇧"
  },
  {
    id: 52,
    name: "The Product Podcast (Product School)",
    category: "Product",
    description: "Podcast da Product School com entrevistas sinceras com executivos de produto das maiores empresas de tecnologia do mundo, compartilhando estratégias e práticas de gestão de produtos",
    url: "https://productschool.com/resources/product-podcast",
    spotifyUrl: "https://open.spotify.com/show/1XBrhVLsQOIAv3KFBqnzrX",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  },
  {
    id: 53,
    name: "UI Breakfast: UI/UX Podcast",
    category: "UX",
    description: "Podcast da designer Jane Portman sobre UX/UI e estratégia de produto. Conversas empolgantes com especialistas sobre design de interfaces, SaaS, marketing e muito mais, com dicas acionáveis para aplicar no seu negócio",
    url: "https://uibreakfast.com",
    spotifyUrl: "https://open.spotify.com/show/2H3wF7LQY9sYLrxR0dc7Ga",
    imageUrl: "podcast.png",
    language: "Inglês",
    country: "Estados Unidos",
    flag: "🇺🇸"
  }
]
